apiVersion: apps/v1
kind: Deployment
metadata:
  name: ep-mern-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ep-mern-rabbitmq
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: ep-mern-rabbitmq
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ep-mern-rabbitmq
        image: azurecontainerlorde.azurecr.io/ep-mern-rabbitmq:${BUILD_TAG}
        ports:
        - containerPort: 15672
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: ep-mern-rabbitmq
spec:
  type: LoadBalancer
  ports:
  - port: 15672
  selector:
    app: ep-mern-rabbitmq